// Code generated by thriftrw v1.0.0
// @generated

package dosa

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type Dosa_CheckSchemaStatus_Args struct {
	Request *CheckSchemaStatusRequest `json:"request,omitempty"`
}

func (v *Dosa_CheckSchemaStatus_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Request != nil {
		w, err = v.Request.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _CheckSchemaStatusRequest_Read(w wire.Value) (*CheckSchemaStatusRequest, error) {
	var v CheckSchemaStatusRequest
	err := v.FromWire(w)
	return &v, err
}

func (v *Dosa_CheckSchemaStatus_Args) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Request, err = _CheckSchemaStatusRequest_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *Dosa_CheckSchemaStatus_Args) String() string {
	var fields [1]string
	i := 0
	if v.Request != nil {
		fields[i] = fmt.Sprintf("Request: %v", v.Request)
		i++
	}
	return fmt.Sprintf("Dosa_CheckSchemaStatus_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *Dosa_CheckSchemaStatus_Args) MethodName() string {
	return "checkSchemaStatus"
}

func (v *Dosa_CheckSchemaStatus_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var Dosa_CheckSchemaStatus_Helper = struct {
	Args           func(request *CheckSchemaStatusRequest) *Dosa_CheckSchemaStatus_Args
	IsException    func(error) bool
	WrapResponse   func(*CheckSchemaStatusResponse, error) (*Dosa_CheckSchemaStatus_Result, error)
	UnwrapResponse func(*Dosa_CheckSchemaStatus_Result) (*CheckSchemaStatusResponse, error)
}{}

func init() {
	Dosa_CheckSchemaStatus_Helper.Args = func(request *CheckSchemaStatusRequest) *Dosa_CheckSchemaStatus_Args {
		return &Dosa_CheckSchemaStatus_Args{Request: request}
	}
	Dosa_CheckSchemaStatus_Helper.IsException = func(err error) bool {
		switch err.(type) {
		case *BadRequestError:
			return true
		case *InternalServerError:
			return true
		default:
			return false
		}
	}
	Dosa_CheckSchemaStatus_Helper.WrapResponse = func(success *CheckSchemaStatusResponse, err error) (*Dosa_CheckSchemaStatus_Result, error) {
		if err == nil {
			return &Dosa_CheckSchemaStatus_Result{Success: success}, nil
		}
		switch e := err.(type) {
		case *BadRequestError:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for Dosa_CheckSchemaStatus_Result.ClientError")
			}
			return &Dosa_CheckSchemaStatus_Result{ClientError: e}, nil
		case *InternalServerError:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for Dosa_CheckSchemaStatus_Result.ServerError")
			}
			return &Dosa_CheckSchemaStatus_Result{ServerError: e}, nil
		}
		return nil, err
	}
	Dosa_CheckSchemaStatus_Helper.UnwrapResponse = func(result *Dosa_CheckSchemaStatus_Result) (success *CheckSchemaStatusResponse, err error) {
		if result.ClientError != nil {
			err = result.ClientError
			return
		}
		if result.ServerError != nil {
			err = result.ServerError
			return
		}
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type Dosa_CheckSchemaStatus_Result struct {
	Success     *CheckSchemaStatusResponse `json:"success,omitempty"`
	ClientError *BadRequestError           `json:"clientError,omitempty"`
	ServerError *InternalServerError       `json:"serverError,omitempty"`
}

func (v *Dosa_CheckSchemaStatus_Result) ToWire() (wire.Value, error) {
	var (
		fields [3]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if v.ClientError != nil {
		w, err = v.ClientError.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if v.ServerError != nil {
		w, err = v.ServerError.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 2, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("Dosa_CheckSchemaStatus_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _CheckSchemaStatusResponse_Read(w wire.Value) (*CheckSchemaStatusResponse, error) {
	var v CheckSchemaStatusResponse
	err := v.FromWire(w)
	return &v, err
}

func (v *Dosa_CheckSchemaStatus_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _CheckSchemaStatusResponse_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.ClientError, err = _BadRequestError_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 2:
			if field.Value.Type() == wire.TStruct {
				v.ServerError, err = _InternalServerError_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if v.ClientError != nil {
		count++
	}
	if v.ServerError != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("Dosa_CheckSchemaStatus_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *Dosa_CheckSchemaStatus_Result) String() string {
	var fields [3]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	if v.ClientError != nil {
		fields[i] = fmt.Sprintf("ClientError: %v", v.ClientError)
		i++
	}
	if v.ServerError != nil {
		fields[i] = fmt.Sprintf("ServerError: %v", v.ServerError)
		i++
	}
	return fmt.Sprintf("Dosa_CheckSchemaStatus_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *Dosa_CheckSchemaStatus_Result) MethodName() string {
	return "checkSchemaStatus"
}

func (v *Dosa_CheckSchemaStatus_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
