// Code generated by thriftrw v1.5.0. DO NOT EDIT.
// @generated

package dosa

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.5.0", "github.com/uber/dosa-idl/.gen/dosa")
}
