// Code generated by thriftrw v1.0.0
// @generated

package dosa

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.0.0", "github.com/uber/dosa-idl/.gen/dosa")
}
